name: "Build and Push"

on:
  pull_request:
#  push:
#    branches:
#      - master
#    paths:
#      - 'docker/**'

jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [php, chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Log In to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./docker/${{ matrix.image }}
          push: true
          tags: |
            ${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
            ${{ github.repository }}/${{ matrix.image }}:latest
          platforms: linux/amd64,linux/arm64